
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Label label1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView texto;

	private global::Gtk.Label label2;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView desplazamiento;

	private global::Gtk.Label label3;

	private global::Gtk.Label label4;

	private global::Gtk.ScrolledWindow GtkScrolledWindow2;

	private global::Gtk.TextView texto_cifrado;

	private global::Gtk.Label label5;

	private global::Gtk.Label label6;

	private global::Gtk.ScrolledWindow GtkScrolledWindow3;

	private global::Gtk.TextView texto_inverso;

	private global::Gtk.Label label7;

	private global::Gtk.Label label8;

	private global::Gtk.ScrolledWindow GtkScrolledWindow4;

	private global::Gtk.TextView grupo;

	private global::Gtk.Label label9;

	private global::Gtk.ScrolledWindow GtkScrolledWindow5;

	private global::Gtk.TextView texto_grupos;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Texto");
		this.fixed1.Add(this.label1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
		w1.X = 166;
		w1.Y = 8;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.texto = new global::Gtk.TextView();
		this.texto.WidthRequest = 250;
		this.texto.HeightRequest = 100;
		this.texto.CanFocus = true;
		this.texto.Events = ((global::Gdk.EventMask)(2048));
		this.texto.Name = "texto";
		this.GtkScrolledWindow.Add(this.texto);
		this.fixed1.Add(this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
		w3.X = 65;
		w3.Y = 41;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Cifrado Cesar");
		this.fixed1.Add(this.label2);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
		w4.X = 27;
		w4.Y = 206;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.desplazamiento = new global::Gtk.TextView();
		this.desplazamiento.WidthRequest = 150;
		this.desplazamiento.CanFocus = true;
		this.desplazamiento.Name = "desplazamiento";
		this.GtkScrolledWindow1.Add(this.desplazamiento);
		this.fixed1.Add(this.GtkScrolledWindow1);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow1]));
		w6.X = 28;
		w6.Y = 268;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Desplazamiento");
		this.fixed1.Add(this.label3);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
		w7.X = 28;
		w7.Y = 234;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Texto Cifrado");
		this.fixed1.Add(this.label4);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label4]));
		w8.X = 30;
		w8.Y = 337;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.texto_cifrado = new global::Gtk.TextView();
		this.texto_cifrado.WidthRequest = 250;
		this.texto_cifrado.HeightRequest = 100;
		this.texto_cifrado.CanFocus = true;
		this.texto_cifrado.Name = "texto_cifrado";
		this.GtkScrolledWindow2.Add(this.texto_cifrado);
		this.fixed1.Add(this.GtkScrolledWindow2);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow2]));
		w10.X = 31;
		w10.Y = 363;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Cifrado Inverso");
		this.fixed1.Add(this.label5);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label5]));
		w11.X = 394;
		w11.Y = 10;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Texto Cifrado");
		this.fixed1.Add(this.label6);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label6]));
		w12.X = 394;
		w12.Y = 37;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow3.WidthRequest = 250;
		this.GtkScrolledWindow3.HeightRequest = 100;
		this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
		this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
		this.texto_inverso = new global::Gtk.TextView();
		this.texto_inverso.CanFocus = true;
		this.texto_inverso.Name = "texto_inverso";
		this.GtkScrolledWindow3.Add(this.texto_inverso);
		this.fixed1.Add(this.GtkScrolledWindow3);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow3]));
		w14.X = 395;
		w14.Y = 76;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Cifrado en grupos");
		this.fixed1.Add(this.label7);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label7]));
		w15.X = 396;
		w15.Y = 207;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Grupos");
		this.fixed1.Add(this.label8);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label8]));
		w16.X = 396;
		w16.Y = 239;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow4 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow4.Name = "GtkScrolledWindow4";
		this.GtkScrolledWindow4.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow4.Gtk.Container+ContainerChild
		this.grupo = new global::Gtk.TextView();
		this.grupo.WidthRequest = 150;
		this.grupo.CanFocus = true;
		this.grupo.Name = "grupo";
		this.GtkScrolledWindow4.Add(this.grupo);
		this.fixed1.Add(this.GtkScrolledWindow4);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow4]));
		w18.X = 396;
		w18.Y = 277;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label9 = new global::Gtk.Label();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Texto Cifrado");
		this.fixed1.Add(this.label9);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label9]));
		w19.X = 397;
		w19.Y = 346;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow5 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow5.Name = "GtkScrolledWindow5";
		this.GtkScrolledWindow5.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow5.Gtk.Container+ContainerChild
		this.texto_grupos = new global::Gtk.TextView();
		this.texto_grupos.WidthRequest = 250;
		this.texto_grupos.HeightRequest = 100;
		this.texto_grupos.CanFocus = true;
		this.texto_grupos.Name = "texto_grupos";
		this.GtkScrolledWindow5.Add(this.texto_grupos);
		this.fixed1.Add(this.GtkScrolledWindow5);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow5]));
		w21.X = 394;
		w21.Y = 385;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 840;
		this.DefaultHeight = 525;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.texto.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler(this.OnTextoKeyReleaseEvent);
	}
}
